name: documentation
run-name: ${{ github.actor }} is trying to build documentation.

on: [push, pull_request, workflow_dispatch]

env:
  
  MAIN_BRANCH: 'main' # Have this specified in some other file.
  SECONDARY_BRANCH: 'develop' # Have this specified in some other file.
  TEMP_WEBSITE_FOLDER: '.website'
  SECONDARY_SITE_DIRECTORY: 'dev'
  #main_dirs: '/home/runner/work/TestingGithub/TestingGithub' <-- This is  ${{github.env.GITHUB_WORKSPACE}}

  BRANCH_NAME: ${{ github.head_ref || github.ref_name}}
  IS_MAIN_SITE_BRANCH: ${{ github.env.BRANCH_NAME == github.env.MAIN_BRANCH}}
  IS_SECONDARY_SITE_BRANCH: ${{github.env.BRANCH_NAME == github.env.SECONDARY_BRANCH}}
  MUST_REGENERATE_SITE: ${{github.env.IS_MAIN_SITE_BRANCH || github.env.IS_SECONDARY_SITE_BRANCH}}

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push' && (github.env.BRANCH_NAME == github.env.MAIN_BRANCH || github.env.BRANCH_NAME == github.env.SECONDARY_BRANCH)}}

    steps:
      
      - name: Setup python
        uses: actions/setup-python@v5

      - name: Setup Directory Structure
        run: |
          #main_dirs=`pwd`
          pwd 
          echo $GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE/$MAIN_BRANCH
          mkdir $MAIN_BRANCH
          mkdir $SECONDARY_BRANCH
          mkdir $TEMP_WEBSITE_FOLDER
          echo local check
          echo ${{github.workspace}}
          ls -a
          echo main check
          ls -a $main_dirs
      - name: Test thing
        run: |
          pwd
          ls -a $GITHUB_WORKSPACE

      - name: Install General dependencies
        run: |
          pwd
          ls -a ${{github.workspace}}
          pip install poetry
          echo ${{github.workspace}}
          
      
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: ${{env.MAIN_BRANCH}}
          path: ${{github.workspace}}/${{env.MAIN_BRANCH}}

      - name: 'MAIN SITE: Install dependencies with Sphinx'
        run: |
          ls -a ${{github.workspace}}
          pwd
          cd ${{github.workspace}}/${{env.MAIN_BRANCH}}
          poetry install --with gh_docs --no-root

      - name: 'MAIN SITE: Sphinx build'
        run: |
        
          poetry run sphinx-build docs/sphinx/source docs/sphinx/build
          echo "${{github.workspace}}/${{env.TEMP_WEBSITE_FOLDER}}"
          cp -r docs/sphinx/build ${{github.workspace}}/${{env.TEMP_WEBSITE_FOLDER}}
          
          cd $main_dirs

      - name: Checkout Secondary Branch
        uses: actions/checkout@v4
        with:
          ref: ${{env.SECONDARY_BRANCH}}
          path: ${{github.workspace}} / ${{env.SECONDARY_BRANCH}}

      - name: 'SECONDARY SITE: Install dependencies with Sphinx'
        run: |
          ls -a ${{github.workspace}}
          pwd
          poetry install --with gh_docs --no-root
  
      - name: 'SECONDARY SITE: Sphinx build'
        run: |
          poetry run sphinx-build docs/sphinx/source $main_dirs/$TEMP_WEBSITE_FOLDER/$SECONDARY_SITE_DIRECTORY
          cd ..

      - name: Deploy Combined Website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.env.TEMP_WEBSITE_FOLDER }}
          force_orphan: true