name: documentation
run-name: ${{ github.actor }} is trying to build documentation.

on: [push, pull_request, workflow_dispatch]

env:
  
  MAIN_BRANCH: 'main' # Have this specified in some other file.
  SECONDARY_BRANCH: 'develop' # Have this specified in some other file.
  TEMP_WEBSITE_FOLDER: '.website'
  SECONDARY_SITE_DIRECTORY: 'dev'
  #main_dirs: '/home/runner/work/TestingGithub/TestingGithub's <-- This is  ${{github.env.GITHUB_WORKSPACE}}

  BRANCH_NAME: ${{ github.head_ref || github.ref_name}}
  IS_MAIN_SITE_BRANCH: ${{ github.env.BRANCH_NAME == github.env.MAIN_BRANCH}}
  IS_SECONDARY_SITE_BRANCH: ${{github.env.BRANCH_NAME == github.env.SECONDARY_BRANCH}}
  MUST_REGENERATE_SITE: ${{github.env.IS_MAIN_SITE_BRANCH || github.env.IS_SECONDARY_SITE_BRANCH}}

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push' && (github.env.BRANCH_NAME == github.env.MAIN_BRANCH || github.env.BRANCH_NAME == github.env.SECONDARY_BRANCH)}}
        #Need to fix this line so it works when push to secondary branch
    steps:
      
      - name: Setup python
        uses: actions/setup-python@v5

      - name: Setup Directory Structure
        run: |
          mkdir $MAIN_BRANCH
          mkdir $SECONDARY_BRANCH
          mkdir $TEMP_WEBSITE_FOLDER

      - name: Install General dependencies
        run: |
          pip install poetry
          
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: ${{env.MAIN_BRANCH}}
          path: ${{github.workspace}}/${{env.MAIN_BRANCH}}

      - name: 'MAIN SITE: Install dependencies with Sphinx'
        run: |
          cd ${{github.workspace}}/${{env.MAIN_BRANCH}}
          poetry install --with gh_docs --no-root

      - name: 'MAIN SITE: Sphinx build'
        run: |
          cd ${{github.workspace}}/${{env.MAIN_BRANCH}}
          poetry run sphinx-build docs/sphinx/source docs/sphinx/build
          cp -r docs/sphinx/build/* ${{github.workspace}}/${{env.TEMP_WEBSITE_FOLDER}}

      - name: Checkout Secondary Branch
        uses: actions/checkout@v4
        with:
          ref: ${{env.SECONDARY_BRANCH}}
          path: ${{github.workspace}}/${{env.SECONDARY_BRANCH}}

      - name: 'SECONDARY SITE: Install dependencies with Sphinx'
        run: |
          ls -a ${{github.workspace}}
          cd ${{github.workspace}}/${{env.SECONDARY_BRANCH}}
          pwd
          poetry install --with gh_docs --no-root
  
      - name: 'SECONDARY SITE: Sphinx build'
        run: |
          cd ${{github.workspace}}/${{env.SECONDARY_BRANCH}}
          poetry run sphinx-build docs/sphinx/source ${{github.workspace}}/${{env.TEMP_WEBSITE_FOLDER}}/${{env.SECONDARY_SITE_DIRECTORY}}
          

      - name: Deploy Combined Website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.TEMP_WEBSITE_FOLDER }}
          force_orphan: true