name: quick test
run-name: ${{ github.actor }} is trying to test stuff.

on: [push, pull_request, workflow_dispatch]

env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name}}
    MAIN_BRANCH: 'main' # Have this specified in some other file.
    SECONDARY_BRANCH: 'develop' # Have this specified in some other file.
    IS_MAIN_SITE_BRANCH: ${{ github.env.BRANCH_NAME == github.env.MAIN_BRANCH}}
    IS_SECONDARY_SITE_BRANCH: ${{github.env.BRANCH_NAME == github.env.SECONDARY_BRANCH}}
    MUST_REGENERATE_SITE: ${{github.env.IS_MAIN_SITE_BRANCH || github.env.IS_SECONDARY_SITE_BRANCH}}

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo ${{github.env.BRANCH_NAME}}
            echo "Is Push ${{github.event_name == 'push'}}"
            echo "main ${{format('{0}',github.env.MAIN_BRANCH)}}"
            echo "secondary ${{github.env.SECONDARY_BRANCH}}"
            echo "is main ${{github.env.IS_MAIN_SITE_BRANCH}}"
            echo "is seccondary ${{github.env.BRANCH_NAME == github.env.SECONDARY_BRANCH}}"
            echo "is must regenerate ${{github.env.MUST_REGENERATE_SITE}}"

